CREATE TABLE IF NOT EXISTS alexa_response (
	id			SERIAL		PRIMARY KEY,
	name	TEXT,
	link	TEXT,
	settings	TEXT,
	timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS world_state (
	id			SERIAL		PRIMARY KEY,
	planetname	TEXT,
	lookingat 	TEXT,
	pressure 	FLOAT DEFAULT 0.0,
	temperature FLOAT DEFAULT 0.0,
	gravity FLOAT DEFAULT 0.0,
	n2level FLOAT DEFAULT 0.0,
	co2level FLOAT DEFAULT 0.0,
	o2level FLOAT DEFAULT 0.0,
	windspeed FLOAT DEFAULT 0.0,
	isdaytime	BOOLEAN DEFAULT TRUE NOT NULL,
	islighton	BOOLEAN DEFAULT TRUE NOT NULL,
	isdrillon	BOOLEAN DEFAULT TRUE NOT NULL,
	settings	TEXT,
	action		TEXT,
	timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscription (
	id			SERIAL		PRIMARY KEY,
	name		TEXT,
	verified 	BOOLEAN DEFAULT FALSE,
	email		TEXT NOT NULL,
	timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP
);